global:
  scrape_interval: 5s
scrape_configs:
  - job_name: "node-example-app"
    static_configs:
      - targets: ["node-example-app:8080"]
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]