apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    editable: true
  
  - name: loki
    access: proxy
    type: loki
    url: http://loki:3100
    basicAuth: false
    readOnly: false
    jsonData:
      keepCookies: []