
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varLogs
      __path__: /var/log/*log
- job_name: node-example-app
  static_configs:
  - targets:
      - localhost
    labels:
      job: node-example-app
      __path__: /backend/logs/dev.log
